// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "helloworldCannyProcess.h"

#include <dtkCore/dtkAbstractProcessFactory.h>
#include <dtkCore/dtkSmartPointer.h>

#include <dtkCore/dtkAbstractDataFactory.h>
#include <dtkCore/dtkAbstractData.h>
#include <dtkCore/dtkAbstractProcess.h>

#include <medMetaDataKeys.h>

#include <itkCannyEdgeDetectionImageFilter.h>
#include <itkCastImageFilter.h>



// /////////////////////////////////////////////////////////////////
// helloworldCannyProcessPrivate
// /////////////////////////////////////////////////////////////////

class helloworldCannyProcessPrivate
{
public:
    helloworldCannyProcess *parent;
    helloworldCannyProcessPrivate(helloworldCannyProcess *p) {parent = p;}

    dtkSmartPointer <dtkAbstractData> input;
    dtkSmartPointer <dtkAbstractData> output;
    double variance;

    itk::CStyleCommand::Pointer callback;
    static void eventCallback(itk::Object* caller, const itk::EventObject& event, void* clientData);
};


void
helloworldCannyProcessPrivate::eventCallback(itk::Object* caller, const itk::EventObject& event, void* clientData)
{
    helloworldCannyProcessPrivate *d = reinterpret_cast<helloworldCannyProcessPrivate *> (clientData);
    itk::ProcessObject * processObject = ( itk::ProcessObject* ) caller;
    d->parent->emitProgressed (static_cast<int>((processObject->GetProgress() * 100)));
}

// /////////////////////////////////////////////////////////////////
// helloworldCannyProcess
// /////////////////////////////////////////////////////////////////

helloworldCannyProcess::helloworldCannyProcess(void) : dtkAbstractProcess(), d(new helloworldCannyProcessPrivate(this))
{
    d->variance = 12;
}

helloworldCannyProcess::~helloworldCannyProcess(void)
{
    delete d;
    d = NULL;
}

void helloworldCannyProcess::emitProgressed(const int progression)
{
    emit progressed(progression);
    qDebug() << "canny Progression" << progression;

}

bool helloworldCannyProcess::registered(void)
{
    return dtkAbstractProcessFactory::instance()->registerProcessType("helloworldCannyProcess", createhelloworldCannyProcess);
}

QString helloworldCannyProcess::description(void) const
{
    return "helloworldCannyProcess";
}

void helloworldCannyProcess::setInput ( dtkAbstractData *data )
{
    if ( !data )
        return;

    qDebug()<<"set Data !!!";
    d->input = data;
}

void helloworldCannyProcess::setParameter ( double  data, int channel )
{
    d->variance = (unsigned int)data;
}

int helloworldCannyProcess::update ( void )
{
    if ( !d->input )
    {
        qDebug() << "in update method : d->input is NULL";
        return -1;
    }

    d->callback = itk::CStyleCommand::New();
    d->callback->SetClientData((void*) this);
    d->callback->SetCallback(helloworldCannyProcessPrivate::eventCallback);

    QString type = QString (d->input->identifier());

    if ( type == "itkDataImageChar3" )
    {
        runCanny<itk::Image<char, 3> >();
    }
    else if ( type == "itkDataImageUChar3" )
    {
       runCanny<itk::Image<unsigned char, 3> >();
    }
    else if ( type == "itkDataImageShort3" )
    {
        runCanny<itk::Image<short, 3> >();
    }
    else if ( type == "itkDataImageUShort3" )
    {
        runCanny<itk::Image<unsigned short, 3> >();
    }
    else if ( type == "itkDataImageInt3" )
    {
        runCanny<itk::Image<int, 3> >();
    }
    else if ( type == "itkDataImageUInt3" )
    {
        runCanny<itk::Image<unsigned int, 3> >();
    }
    else if ( type == "itkDataImageLong3" )
    {
        runCanny<itk::Image<long, 3> >();
    }
    else if ( type == "itkDataImageULong3" )
    {
        runCanny<itk::Image<unsigned long, 3> >();
    }
    else if ( type == "itkDataImageFloat3" )
    {
        runCanny<itk::Image<float, 3> >();
    }
    else if ( type == "itkDataImageDouble3" )
    {
        runCanny<itk::Image<double, 3> >();
    }

    return EXIT_SUCCESS;
}

template <class ImageType> void helloworldCannyProcess::runCanny()
{


    //compute canny
    typedef itk::Image<float, 3> RealImageType;
    typedef itk::CastImageFilter <ImageType, RealImageType> CastFilter;
    typename CastFilter::Pointer castFilter = CastFilter::New();
    castFilter->SetInput(dynamic_cast<ImageType*>((itk::Object*)(d->input->data())));
    castFilter->Update();

    typedef itk::CannyEdgeDetectionImageFilter <RealImageType, RealImageType> CannyFilter;
    typename CannyFilter::Pointer cannyFilter = CannyFilter::New();
    cannyFilter->SetVariance(d->variance);
    cannyFilter->SetInput(castFilter->GetOutput());
    cannyFilter->AddObserver(itk::ProgressEvent(), d->callback);

    cannyFilter->Update();

    // update output data
    d->output = dtkAbstractDataFactory::instance()->createSmartPointer ("itkDataImageFloat3");
    d->output->setData(cannyFilter->GetOutput());
}

dtkAbstractData * helloworldCannyProcess::output ( void )
{
    return ( d->output );
}


// /////////////////////////////////////////////////////////////////
// Type instantiation
// /////////////////////////////////////////////////////////////////

dtkAbstractProcess *createhelloworldCannyProcess(void)
{
    return new helloworldCannyProcess;
}


