// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "helloWorldCannyProcess.h"

#include <dtkCore/dtkAbstractProcessFactory.h>
#include <dtkCore/dtkSmartPointer.h>

#include <dtkCore/dtkAbstractDataFactory.h>
#include <dtkCore/dtkAbstractData.h>
#include <dtkCore/dtkAbstractProcess.h>

#include <medMetaDataKeys.h>

#include <itkCannyEdgeDetectionImageFilter.h>
#include <itkCastImageFilter.h>



// /////////////////////////////////////////////////////////////////
// helloWorldCannyProcessPrivate
// /////////////////////////////////////////////////////////////////

class helloWorldCannyProcessPrivate
{
public:
    helloWorldCannyProcess *parent;
    helloWorldCannyProcessPrivate(helloWorldCannyProcess *p) {parent = p;}

    dtkSmartPointer <dtkAbstractData> input;
    dtkSmartPointer <dtkAbstractData> output;
    double variance;

    itk::CStyleCommand::Pointer callback;
    static void eventCallback(itk::Object* caller, const itk::EventObject& event, void* clientData);
};


void
helloWorldCannyProcessPrivate::eventCallback(itk::Object* caller, const itk::EventObject& event, void* clientData)
{
    helloWorldCannyProcessPrivate *d = reinterpret_cast<helloWorldCannyProcessPrivate *> (clientData);
    itk::ProcessObject * processObject = ( itk::ProcessObject* ) caller;
    d->parent->emitProgressed (static_cast<int>((processObject->GetProgress() * 100)));
}

// /////////////////////////////////////////////////////////////////
// helloWorldCannyProcess
// /////////////////////////////////////////////////////////////////

helloWorldCannyProcess::helloWorldCannyProcess(void) : dtkAbstractProcess(), d(new helloWorldCannyProcessPrivate(this))
{
    d->variance = 0.5;
}

helloWorldCannyProcess::~helloWorldCannyProcess(void)
{
    delete d;
    d = NULL;
}

void helloWorldCannyProcess::emitProgressed(const int progression)
{
    emit progressed(progression);
    qDebug() << "canny Progression" << progression;

}

bool helloWorldCannyProcess::registered(void)
{
    return dtkAbstractProcessFactory::instance()->registerProcessType("helloWorldCannyProcess", createhelloWorldCannyProcess);
}

QString helloWorldCannyProcess::description(void) const
{
    return "helloWorldCannyProcess";
}

void helloWorldCannyProcess::setInput ( dtkAbstractData *data )
{
    if ( !data )
        return;

    qDebug()<<"set Data !!!";
    d->input = data;
}

void helloWorldCannyProcess::setParameter ( double  data, int channel )
{
    d->variance = (unsigned int)data;
}

int helloWorldCannyProcess::update ( void )
{
    if ( !d->input )
    {
        qDebug() << "in update method : d->input is NULL";
        return -1;
    }

    d->callback = itk::CStyleCommand::New();
    d->callback->SetClientData((void*) this);
    d->callback->SetCallback(helloWorldCannyProcessPrivate::eventCallback);

    QString type = QString (d->input->identifier());

    if ( type == "itkDataImageChar3" )
    {
        runCanny<itk::Image<char, 3> >();
    }
    else if ( type == "itkDataImageUChar3" )
    {
       runCanny<itk::Image<unsigned char, 3> >();
    }
    else if ( type == "itkDataImageShort3" )
    {
        runCanny<itk::Image<short, 3> >();
    }
    else if ( type == "itkDataImageUShort3" )
    {
        runCanny<itk::Image<unsigned short, 3> >();
    }
    else if ( type == "itkDataImageInt3" )
    {
        runCanny<itk::Image<int, 3> >();
    }
    else if ( type == "itkDataImageUInt3" )
    {
        runCanny<itk::Image<unsigned int, 3> >();
    }
    else if ( type == "itkDataImageLong3" )
    {
        runCanny<itk::Image<long, 3> >();
    }
    else if ( type == "itkDataImageULong3" )
    {
        runCanny<itk::Image<unsigned long, 3> >();
    }
    else if ( type == "itkDataImageFloat3" )
    {
        runCanny<itk::Image<float, 3> >();
    }
    else if ( type == "itkDataImageDouble3" )
    {
        runCanny<itk::Image<double, 3> >();
    }

    return EXIT_SUCCESS;
}

template <class ImageType> void helloWorldCannyProcess::runCanny()
{


    //compute canny
    typedef itk::Image<float, 3> RealImageType;
    typedef itk::CastImageFilter <ImageType, RealImageType> CastFilter;
    typename CastFilter::Pointer castFilter = CastFilter::New();
    castFilter->SetInput(dynamic_cast<ImageType*>((itk::Object*)(d->input->data())));
    castFilter->Update();

    typedef itk::CannyEdgeDetectionImageFilter <RealImageType, RealImageType> CannyFilter;
    typename CannyFilter::Pointer cannyFilter = CannyFilter::New();
    cannyFilter->SetVariance(d->variance);
    cannyFilter->SetInput(castFilter->GetOutput());
    cannyFilter->AddObserver(itk::ProgressEvent(), d->callback);

    cannyFilter->Update();

    // update output data
    d->output = dtkAbstractDataFactory::instance()->createSmartPointer ("itkDataImageFloat3");
    d->output->setData(cannyFilter->GetOutput());
}

dtkAbstractData * helloWorldCannyProcess::output ( void )
{
    return ( d->output );
}


// /////////////////////////////////////////////////////////////////
// Type instantiation
// /////////////////////////////////////////////////////////////////

dtkAbstractProcess *createhelloWorldCannyProcess(void)
{
    return new helloWorldCannyProcess;
}


